### ISSUE TITLE
AUTH_LDAP_SERVER_URI must be a list

### ISSUE THREAD

**Issue by sstark** [susundberg/django-auth-ldap-ad#2]
even if it's only one URI. The default value and README.md are not so clear about this. If in settings.py I use:

```
'ldap://myserver'
```

instead of:

```
['ldap://myserver']
```

I get LDAPError 2, _'No such file or directory'_ and 34, _'Numerical result out of range'_.

**Comment by susundberg** [comment]
Thanks for the input. Fixed in my new commit (873e5fd)
