### ISSUE TITLE
Create a pypi package

### ISSUE THREAD

**Issue by frague59** [susundberg/django-auth-ldap-ad#8]
I'm using a copy of your project in many projects I build, and you have done a great job ! 
This package is really awesome... and easy to use !

Do you project to put it into pypi ? We could install it directly : 
`$ pip install django-auth-ldap-ad`
This would be amazing...

Thanks !

**Comment by susundberg** [comment]
Hi!
Nice to hear you find it usefull.

Pypi package indeed would be great - but i am having trouble to find any freetime for this project. If you can help with making the package, i would be more than happy to merge the pull request.

At least https://github.com/pebble/libpebble2 has super nice integration with pypi and the CI travis!

Cheers, 
Pauli

**Comment by frague59** [comment]
Hi, 

I've created an initial version of the package:

https://testpypi.python.org/pypi/django-auth-ldap-ad/0.1.0a1

I've to test it...

**Comment by susundberg** [comment]
Hi! Super, nice work!

**Comment by susundberg** [comment]
I'll close this as no news. I'll probably ping you if there are changes required.

**Comment by susundberg** [comment]
Hi!

Sorry to come back this as late as this, but @frague59  could you transfer the ownership of the pypi-package to me. I have pypi account with name of "susundberg" (https://pypi.python.org/id/susundberg).

Thanks!
