### ISSUE TITLE
cac authenication

### ISSUE THREAD

**Issue by ghost** [susundberg/django-auth-ldap-ad#9]
I would like cac/pki certification with my django app.

Any suggestions or pointers?

I found [this ](http://stackoverflow.com/questions/3745291/django-and-common-access-cards-cac) but they just said:
"I just did this today by subclassing django.contrib.auth.middleware.RemoteUserMiddleware and changed the header property to the one I had set in my apache conf. I just added the django.contrib.auth.backends.RemoteUserBackend and my middleware to the settings and it works perfectly."

seems this might be similar to ldap authentication as well?

I really don't know much about cac/pki except that I am tired of logging in through username/password...

**Comment by susundberg** [comment]
No sorry, i would start with the same thing as you -- googling it. You might also want to try community support on Slack / irc.
